[profile.default]
src = "src"
out = "out"
libs = ["lib"]
eth_rpc_url = "localhost:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
